---
apiVersion: v1
kind: Namespace
metadata:
  name: xdp-tools-test
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: xdp-net
  namespace: xdp-tools-test
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "eth0",
    "mode": "bridge",
    "ipam": {
      "type": "static",
      "addresses": [
        { "address": "10.10.0.10/24", "gateway": "10.10.0.1" }
      ]
    }
  }'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xdp-redirect-code
  namespace: xdp-tools-test
data:
  xdp_redirect.c: |
    #include <linux/bpf.h>
    #include <bpf/bpf_helpers.h>

    struct {
        __uint(type, BPF_MAP_TYPE_DEVMAP);
        __uint(max_entries, 2);
        __type(key, __u32);
        __type(value, __u32);
    } tx_port SEC(".maps");

    SEC("xdp")
    int xdp_redirect_prog(struct xdp_md *ctx) {
        __u32 index = 1;
        return bpf_redirect_map(&tx_port, index, 0);
    }

    char LICENSE[] SEC("license") = "GPL";
---
apiVersion: v1
kind: Pod
metadata:
  name: xdp-a
  namespace: xdp-tools-test
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "xdp-net" }]'
spec:
  hostNetwork: false
  containers:
    - name: main
      image: quay.io/midu/fedora-xdp-tools:latest
      command: ["/bin/bash", "-c", "sleep infinity"]
      securityContext:
        privileged: true
  initContainers:
    - name: xdp-setup
      image: quay.io/midu/fedora-xdp-tools:latest
      command:
        - /bin/sh
        - -c
        - |
          echo "$XDP_PROG" > /xdp/xdp_redirect.c
          clang -O2 -g -Wall -target bpf -c /xdp/xdp_redirect.c -o /xdp/xdp_redirect.o
          ip link set dev net1 up
          ip addr add 10.10.0.10/24 dev net1
          ip link set dev net1 xdp obj /xdp/xdp_redirect.o sec xdp_redirect_prog
      env:
        - name: XDP_PROG
          valueFrom:
            configMapKeyRef:
              name: xdp-redirect-code
              key: xdp_redirect.c
      volumeMounts:
        - name: xdp-src
          mountPath: /xdp
      securityContext:
        privileged: true
  volumes:
    - name: xdp-src
      emptyDir: {}
